server:
  port: 8000

spring:
  application:
    name: my-zuul-service

zuul:
  routes:
    first-service:
      path: /first-service/**
      url: http://localhost:8081/first-service/
    second-service:
      path: /second-service/**
      url: http://localhost:8082/second-service/
